name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config --global user.email "your@email.com"
          git config --global user.name "Your Name"

      - name: Add Hugging Face remote
        run: |
          git remote add space https://user:${HF_TOKEN}@huggingface.co/spaces/eleffa/demo2
        env:
          HF_TOKEN: ${{ secrets.HF }}

      - name: Push to Hugging Face Hub
        run: |
          git push --force space main
        env:
          HF_TOKEN: ${{ secrets.HF }}
